import AppKit

enum ClipboardCodec {
    static let maxDataSize = 20_000_000

    static func read(from board: NSPasteboard) -> Clip? {
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                        "org.nspasteboard.AutoGeneratedType"]
        guard !(board.types ?? []).contains(where: { excluded.contains($0.rawValue) }) else { return nil }
        // File URLs take priority over an image preview or textual filename.
        if let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return Clip(text: "", content: .files(urls.map(\.path)))
        }
        if let paths = board.propertyList(forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")) as? [String],
           !paths.isEmpty {
            return Clip(text: "", content: .files(paths))
        }
        if let data = board.data(forType: .pdf), !data.isEmpty, data.count <= maxDataSize {
            return Clip(text: "", content: .pdf(data))
        }
        if let data = board.data(forType: .png), !data.isEmpty, data.count <= maxDataSize {
            return Clip(text: "", content: .image(data))
        }
        if let data = board.data(forType: .tiff), data.count <= maxDataSize,
           let image = NSBitmapImageRep(data: data),
           let png = image.representation(using: .png, properties: [:]), png.count <= maxDataSize {
            return Clip(text: "", content: .image(png))
        }
        if let text = board.string(forType: .string), text.utf8.count <= 1_000_000,
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return Clip(text: text)
        }
        return nil
    }

    static func write(_ clip: Clip, to board: NSPasteboard) throws {
        if case .files(let paths) = clip.content {
            guard !paths.isEmpty, paths.allSatisfy({ FileManager.default.fileExists(atPath: $0) }) else {
                throw ClipboardError.missingFile
            }
            board.clearContents()
            guard board.writeObjects(paths.map { NSURL(fileURLWithPath: $0) }) else {
                throw ClipboardError.writeFailed
            }
            return
        }
        board.clearContents()
        let success: Bool
        switch clip.content {
        case .image(let data): success = board.setData(data, forType: .png)
        case .pdf(let data): success = board.setData(data, forType: .pdf)
        case nil: success = board.setString(clip.text, forType: .string)
        case .files: success = false
        }
        guard success else { throw ClipboardError.writeFailed }
    }
}

enum ClipboardError: LocalizedError {
    case missingFile, writeFailed
    var errorDescription: String? {
        switch self {
        case .missingFile: return "An original file was moved or deleted. Copy it again from Finder."
        case .writeFailed: return "Couldn’t put this item on the clipboard."
        }
    }
}
